grails-app/domain/fr/av/mbds/User.groovy
package fr.av.mbds

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired
    String pathProfileImage
    String imageFile

    static hasMany = [matchWon:Game,matchLost:Game, messageSent:Message, messageReceived: Message]
    static mappedBy = [matchWon:'winner', matchLost: 'looser', messageSent: 'author', messageReceived: 'target']

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
        pathProfileImage nullable: true
        imageFile nullable: true
    }

    static mapping = {
	    password column: '`password`'
    }

}

grails-app/controllers/fr/av/mbds/UserController.groovy
package fr.av.mbds

import fr.av.mbds.command.ProfileImageCommand
import fr.av.mbds.impl.UploadFileService
import fr.av.mbds.impl.UserEntityService
import grails.converters.JSON
import grails.plugin.springsecurity.SpringSecurityService
import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException

import java.nio.file.NoSuchFileException

import static org.springframework.http.HttpStatus.*

@Secured('ROLE_ADMIN')
class UserController {
    UploadFileService uploadFileService
    UserService userService
    UserEntityService userEntityService
    SpringSecurityService springSecurityService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE", restore: "PUT"]
    static private relativePathTmp = '/upload/user/tmp/'
    static private relativePathTarget = '/upload/user/'

    def index() {
        respond userService.list(params), model:[userCount: userService.count()]
    }

    def show(Long id) {
        respond userService.get(id)
    }

    def create() {
        respond new User(params)
    }

    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
            // Move image profile if exist
            String url = params.get('imageProfileUrl')
            if(url != ""){
                String imageFileUrl = uploadFileService.moveTmpFile(url, relativePathTmp, relativePathTarget)
                user = userService.updateProfileImage(user.id, user.version, imageFileUrl)
                user = userService.updateImageFile(user.id, user.version, url)
            }
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        } catch (NoSuchFileException e) {
            flash.message = message(code: 'default.file.not.found')
            respond user, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond userService.get(id)
    }

    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            String url = params.get('imageProfileUrl')
            String[] roles = params.get('rolesSelected[]')
            userEntityService.assignRolesToUser(roles,user)
            userService.save(user)
            if(url != ""){
                String imageFileUrl = uploadFileService.moveTmpFile(url, relativePathTmp, relativePathTarget)
                user = userService.updateProfileImage(user.id, user.version, imageFileUrl)
                // delete old image
                if(user.imageFile != null) {
                    uploadFileService.removeFile(user.imageFile, relativePathTarget)
                }
                user = userService.updateImageFile(user.id, user.version, url)
            }

            def currentUser = springSecurityService.currentUser
            if(currentUser.username == user.username) {
                springSecurityService.reauthenticate(currentUser.username)
            }
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        } catch (NoSuchFileException e) {
            flash.message = message(code: 'default.file.not.found')
            respond user, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }
        // Disable and lock user account
        User user = User.findById(id)
        user.enabled = false
        user.accountLocked = true
        userService.save(user)
        //userService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    def restore(Long id) {
        if (id == null) {
            notFound()
            return
        }
        // Enable user
        User user = User.findById(id)
        user.enabled = true
        user.accountLocked = false
        userService.save(user)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.restore.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def editProfileImage(Long id) {
        User user = User.get(id)
        if (!user) {
            notFound()
        }
        [user: user]
    }

    def uploadProfileImage(ProfileImageCommand cmd) {

        if (cmd.hasErrors()) {
            //respond(cmd, model: [user: cmd], view: 'create')
            response.status = 400
            def error = cmd.getErrors().getFieldError("imageFile").getCode()
            render(['error': true, 'message': message(code: error)] as JSON)
        }

        String filename = uploadFileService.uploadFileInTemp(cmd, relativePathTmp)

        Locale locale = request.locale
        //flash.message = crudMessageService.message(CRUD.UPDATE, domainName(locale), pointOfInterest.id, locale)
        render(['filename':filename, 'url': uploadFileService.getUrl(filename, relativePathTmp)] as JSON)
    }
}

grails-app/views/user/_formProfileImage.gsp
<div id="uploadErrorMessage" class="alert alert-danger hidden" role="alert" style="display:none;">
</div>
<div id="previewProfileImage" class="avatarUpload circle"
     style="background-image:url(${this.user.pathProfileImage ?: resource(dir:'images', file:'plus-black-symbol.svg')});
     <g:if test="${this.user.pathProfileImage == null}">
         background-size: 60%;
     </g:if>
     ">
    <input id="imageFile" type="file" name="imageFile"/>

    <div class="loading" style="display:none;">Loading&#8230;</div>
</div>

<asset:javascript src="jquery-2.2.0.min.js"/>
<script>
    $('#previewProfileImage').on('drag dragstart dragend dragover dragenter dragleave drop', function(e) {
        e.preventDefault();
        e.stopPropagation();
    })
        .on('dragover dragenter', function() {
            $(this).addClass('is-dragover');
        })
        .on('dragleave dragend drop', function() {
            $(this).removeClass('is-dragover');
        })
        .on('drop', function(e) {
            let droppedFiles = e.originalEvent.dataTransfer.files;
            if(droppedFiles) {
                sendImage(droppedFiles[0]);
            }
        });

    $('#imageFile').change(function(){
        sendImage($('#imageFile')[0].files[0]);
    });

    function sendImage(file){
        let formulaire = new FormData();
        formulaire.append('imageFile', file);
        $('#uploadErrorMessage').hide();
        $('.loading').show();
        $.ajax({
            url: '${createLink(controller: 'user', action: 'uploadProfileImage')}',
            type: 'POST',
            success: function(data){
                $('#imageProfileUrl').val(data.filename);
                $('#previewProfileImage').css("background-image", "url("+data.url+")");
                $('#previewProfileImage').css("background-size", "cover");
            },
            error: function(data){
                $('#imageFile').val('');
                $('#uploadErrorMessage').text(data.responseJSON.message);
                $('#uploadErrorMessage').show();
            },
            complete: function(data){
                $('.loading').hide();
            },
            data: formulaire,
            cache: false,
            contentType: false,
            processData: false,
            enctype: 'multipart/form-data'
        });
    }
</script>
<asset:stylesheet src="styles.css"/>

grails-app/views/user/_formRole.gsp
<g:set var="roles" value="${fr.av.mbds.Role.findAll()}"/>
<div class="form-group row">
    <label class="col-md-3 col-form-label">Roles</label>

    <div class="col-md-9 col-form-label">
        <g:each var="role" in="${roles}">
            <div class="form-check">
                <input id="roleSelected_${role.authority}" class="form-check-input" name="rolesSelected[]" type="checkbox"
                       value="${role.id}"
                    <g:if test="${user.isAttached()}">
                        <g:each var="userRole" in="${user.getAuthorities()}">
                            <g:if test="${role.id == userRole.id}">
                                checked
                            </g:if>
                        </g:each>
                    </g:if>>
                <label class="form-check-label" for="roleSelected_${role.authority}">${role.authority}</label>
            </div>
        </g:each>

    </div>
</div>

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
    <div class="container-fluid">
        <g:if test="${flash.message}">
            <div class="alert alert-success mx-auto col-10">
                <div>${flash.message}</div>
            </div>
        </g:if>
        <g:hasErrors bean="${this.user}">
            <div class="alert alert-danger mx-auto col-10">
                <ul>
                    <g:eachError bean="${this.user}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                                error="${error}"/></li>
                    </g:eachError>
                </ul>
            </div>
        </g:hasErrors>
        <g:render template="formProfileImage"/>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong><g:message code="default.create.label" args="[entityName]"/></strong></div>
                    <g:form resource="${this.user}" method="POST">
                        <div class="card-body">
                            <g:hiddenField name="version" value="${this.user?.version}"/>
                            <fieldset class="form">
                                <f:all bean="user"
                                       except="matchLost, matchWon, messageSent, messageReceived, pathProfileImage,
                                       imageFile, roles, accountLocked, enabled"/>
                                <g:hiddenField name="imageProfileUrl"/>
                            </fieldset>
                            <g:render template="formRole"/>
                        </div>

                        <div class="card-footer">
                            <button class="btn btn-sm btn-primary" type="submit">
                                <i class="fa fa-dot-circle-o"></i> ${message(code: 'default.button.create.label', default: 'Create')}
                            </button>
                            <button class="btn btn-sm btn-danger" type="reset">
                                <i class="fa fa-ban"></i> Reset</button>
                        </div>

                    </g:form>
                </div>
            </div>
            <!-- /.col-->
        </div>
    </div>
    </body>
</html>

grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<div class="container-fluid">
    <g:if test="${flash.message}">
        <div class="alert alert-success mx-auto col-10">
            <div>${flash.message}</div>
        </div>
    </g:if>
    <g:hasErrors bean="${this.user}">
        <div class="alert alert-danger mx-auto col-10">
            <ul>
                <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
                </g:eachError>
            </ul>
        </div>
    </g:hasErrors>
    <g:render template="formProfileImage"/>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong><g:message code="default.edit.label" args="[entityName]"/></strong></div>
                <g:form resource="${this.user}" method="PUT">
                    <div class="card-body">
                        <g:hiddenField name="version" value="${this.user?.version}"/>
                        <fieldset class="form">
                            <f:all bean="user"
                                   except="matchLost, matchWon, messageSent, messageReceived, pathProfileImage,
                                   imageFile, roles, accountLocked, enabled"/>
                            <g:hiddenField name="imageProfileUrl"/>
                        </fieldset>
                        <g:render template="formRole"/>
                    </div>

                    <div class="card-footer">
                        <button class="btn btn-sm btn-primary" type="submit">
                            <i class="fa fa-dot-circle-o"></i> ${message(code: 'default.button.update.label', default: 'Update')}
                        </button>
                        <button class="btn btn-sm btn-danger" type="reset">
                            <i class="fa fa-ban"></i> Reset</button>
                    </div>

                </g:form>
            </div>
        </div>
        <!-- /.col-->
    </div>
</div>
</body>
</html>

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.list.label" args="['Users']"/></title>
</head>

<body>
<div class="container-fluid">
    <g:if test="${flash.message}">
        <div class="alert alert-success mx-auto col-10">
            <div>${flash.message}</div>
        </div>
    </g:if>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><g:message code="default.list.label" args="['Users']"/></div>

                <div class="card-body">
                    <table id="tableUsers" class="table table-responsive-sm table-hover table-outline mb-0">
                        <thead class="thead-light">
                        <tr>
                            <th class="text-center">
                                <i class="icon-people"></i>
                            </th>
                            <th>User</th>
                            <th>Status</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <g:each var="user" in="${userList}">
                            <tr>
                                <td class="text-center">
                                    <div class="avatar">
                                        <g:if test="${user.pathProfileImage == null}">
                                            <g:img dir="images" file="user.svg" class="img-avatar"/>
                                        </g:if>
                                        <g:else>
                                            <img class="img-avatar" src="${user.pathProfileImage}"/>
                                        </g:else>
                                    </div>
                                </td>
                                <td>
                                    <div>${user.username}</div>
                                </td>
                                <td>
                                    <g:if test="${user.enabled && !user.accountLocked}">
                                        <span class="badge badge-success">Active</span>
                                    </g:if>
                                    <g:else>
                                        <span class="badge badge-danger">Deleted</span>
                                    </g:else>
                                </td>
                                <td>
                                    <g:each var="role" in="${user.getAuthorities()}">
                                        <span class="badge badge-dark">${role.authority}</span>
                                    </g:each>
                                </td>
                                <td>
                                    <div class="row">
                                        <div class="col-4 col-sm-4 col-md-4 col-xl-4">
                                            <a href="<g:createLink controller="user" action="show" params="[id:user.id]" />">
                                                <button class="btn btn-block btn-primary" type="button"><g:message
                                                        code="default.button.show.label"/></button>
                                            </a>
                                        </div>
                                        <div class="col-4 col-sm-4 col-md-4 col-xl-4">
                                            <a href="<g:createLink controller="user" action="edit" params="[id:user.id]" />">
                                                <button class="btn btn-block btn-success" type="button"><g:message code="default.button.edit.label"/></button>
                                            </a>
                                        </div>
                                        <div class="col-4 col-sm-4 col-md-4 col-xl-4">
                                            <g:if test="${user.enabled && !user.accountLocked}">
                                                <form method="post"
                                                      action="<g:createLink controller="user" action="delete"
                                                                            params="[id: user.id]"/>">
                                                    <input type="hidden" name="_method" value="DELETE" id="_method"/>
                                                    <input class="btn btn-block btn-danger" type="submit"
                                                           value="<g:message code="default.button.delete.label"/>"/>
                                                </form>
                                            </g:if>
                                            <g:else>
                                                <form method="post"
                                                      action="<g:createLink controller="user" action="restore"
                                                                            params="[id: user.id]"/>">
                                                    <input type="hidden" name="_method" value="PUT" id="_method"/>
                                                    <input class="btn btn-block btn-secondary" type="submit"
                                                           value="<g:message code="default.button.restore.label"/>"/>
                                                </form>
                                            </g:else>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </g:each>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        $('#tableUsers').DataTable({
            responsive: true,
        });
    });
</script>
</body>
</html>

grails-app/views/user/show.gsp
<!DOCTYPE html>

<html>
<head>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
%{--<f:display bean="user" except="['pathProfileImage', 'password']"/>--}%

    <div class="container-fluid">
        <g:if test="${flash.message}">
            <div class="alert alert-success mx-auto col-10">
                <div>${flash.message}</div>
            </div>
        </g:if>
        <div class="rounded mx-auto d-block">
            <div id="previewProfileImage" class="avatarUpload circle imgProfil"
                 style="background-image:url(${this.user.pathProfileImage ?: resource(dir: 'images', file: 'user.svg')});">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">User's Informations
                        <div class="float-right">
                            <a class="card-header-action delete-badge">
                                <g:form resource="${this.user}" method="DELETE">
                                    <input type="hidden" name="_method" value="DELETE" id="_method"/>
                                    <input class="badge badge-pill badge-danger delete" type="submit"
                                           value="<g:message code="default.button.delete.label"/>">
                                </g:form>
                            </a>
                        </div>
                        <div class="float-right">
                            <a class="card-header-action" href="<g:createLink controller="user" action="edit" params="['id':this.user.id]"/>">
                                <small class="badge badge-pill badge-success edit">Edit</small>
                            </a>
                        </div>
                    </div>


                    <div class="card-body">
                        <div>
                            <p>Name : ${user.username}</p>

                            <p>Enabled : ${user.enabled}</p>

                            <p>Account Expired : ${user.accountExpired}</p>

                            <p>AccountLocked :${user.accountLocked}</p>

                            <p>Password Expired : ${user.passwordExpired}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Won Games</div>

                    <div class="card-body">
                        <table id="tableGamesWon" class="table table-responsive-sm table-hover table-outline mb-0">
                            <thead class="thead-light">
                            <tr>
                                <th>Match number</th>
                                <th>Competitor</th>
                                <th>His score</th>
                                <th>Competitor's score</th>
                            </tr>
                            </thead>
                            <tbody>
                            <g:each var="match" in="${user.matchWon}">
                                <tr>
                                    <td>${match.id}</td>
                                    <td>${match.looser.username}</td>
                                    <td>${match.winnerScore}</td>
                                    <td>${match.looserScore}</td>
                                </tr>
                            </g:each>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Lost Games</div>

                        <div class="card-body">
                            <table id="tableGamesLoose" class="table table-responsive-sm table-hover table-outline mb-0">
                                <thead class="thead-light">
                                <tr>
                                    <th>Match number</th>
                                    <th>Competitor</th>
                                    <th>His score</th>
                                    <th>Competitor's score</th>
                                </tr>
                                </thead>
                                <tbody>
                                <g:each var="match" in="${user.matchLost}">
                                    <tr>
                                        <td>${match.id}</td>
                                        <td>${match.winner.username}</td>
                                        <td>${match.winnerScore}</td>
                                        <td>${match.looserScore}</td>
                                    </tr>
                                </g:each>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>



    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Sent Messages</div>

                <div class="card-body">
                    <table id="tableMessagesSent" class="table table-responsive-sm table-hover table-outline mb-0">
                        <thead class="thead-light">
                        <tr>
                            <th>Date</th>
                            <th>Receiver</th>
                            <th>Content</th>
                            <th>Is Read</th>
                            </tr>
                            </thead>
                            <tbody>
                            <g:each var="message" in="${user.messageSent}">
                                <tr>
                                    <td>${message.dateCreated}</td>
                                    <td>${message.target.username}</td>
                                    <td>${message.content}</td>
                                    <td>${message.isRead}</td>
                                </tr>
                            </g:each>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>



    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Received Messages</div>

                <div class="card-body">
                    <table id="tableMessagesReceived" class="table table-responsive-sm table-hover table-outline mb-0">
                        <thead class="thead-light">
                        <tr>
                            <th>Date</th>
                            <th>Author</th>
                            <th>Content</th>
                            <th>Is Read</th>
                        </tr>
                            </thead>
                            <tbody>
                            <g:each var="message" in="${user.messageReceived}">
                                <tr>
                                    <td>${message.dateCreated}</td>
                                    <td>${message.author.username}</td>
                                    <td>${message.content}</td>
                                    <td>${message.isRead}</td>
                                </tr>
                            </g:each>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>


</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        $('#tableGamesWon').DataTable({
            responsive: true,
        });
    });

    document.addEventListener("DOMContentLoaded", function () {
        $('#tableGamesLoose').DataTable({
            responsive: true,
        });
    });

    document.addEventListener("DOMContentLoaded", function () {
        $('#tableMessagesSent').DataTable({
            responsive: true,
        });
    });

    document.addEventListener("DOMContentLoaded", function () {
        $('#tableMessagesReceived').DataTable({
            responsive: true,
        });
    });

</script>
</body>
</html>