grails-app/domain/fr/av/mbds/Message.groovy
package fr.av.mbds

class Message {

    User author
    User target
    String content
    boolean isRead

    Date dateCreated

    static constraints = {
        target nullable: false
        author nullable: false
        content blank: false
        content  size: 2..15000
    }

    static mapping = {
        isRead defaultValue: false
        content sqlType: 'text'
    }


}

grails-app/controllers/fr/av/mbds/MessageController.groovy
package fr.av.mbds

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException

import static org.springframework.http.HttpStatus.*

@Secured('ROLE_ADMIN')
class MessageController {

    MessageService messageService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index() {
        respond messageService.list(params), model:[messageCount: messageService.count()]
    }

    def show(Long id) {
        respond messageService.get(id)
    }

    def create() {
        respond new Message(params)
    }

    def save(Message messageObj) {
        if (messageObj == null) {
            notFound()
            return
        }

        try {
            messageService.save(messageObj)
        } catch (ValidationException e) {
            respond messageObj.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'message.label', default: 'Message'), messageObj.id])
                redirect messageObj
            }
            '*' { respond messageObj, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond messageService.get(id)
    }

    def update(Message messageObj) {
        if (messageObj == null) {
            notFound()
            return
        }

        try {
            messageService.save(messageObj)
        } catch (ValidationException e) {
            respond messageObj.errors, view: 'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'message.label', default: 'Message'), messageObj.id])
                redirect messageObj
            }
            '*' { respond messageObj, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        messageService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'message.label', default: 'Message'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'message.label', default: 'Message'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

}

grails-app/views/message/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<div class="container-fluid">
    <g:if test="${flash.message}">
        <div class="alert alert-success mx-auto col-10">
            <div>${flash.message}</div>
        </div>
    </g:if>
    <g:hasErrors bean="${this.game}">
        <div class="alert alert-danger mx-auto col-10">
            <ul>
                <g:eachError bean="${this.game}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                            error="${error}"/></li>
                </g:eachError>
            </ul>
        </div>
    </g:hasErrors>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><g:message code="default.create.label" args="[entityName]"/></div>
                <g:form resource="${this.message}" method="POST">
                    <div class="card-body">
                        <f:all bean="message" except="isRead, content"/>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label" for="content">content</label>

                            <div class="col-md-9">
                                <textarea class="form-control" id="content" name="content" rows="9"
                                          placeholder="Content..">${message.content}</textarea>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <button class="btn btn-sm btn-primary" type="submit">
                            <i class="fa fa-dot-circle-o"></i> ${message(code: 'default.button.create.label', default: 'Create')}
                        </button>
                        <button class="btn btn-sm btn-danger" type="reset">
                            <i class="fa fa-ban"></i> Reset</button>
                    </div>
                </g:form>
            </div>
        </div>
    </div>
</body>
</html>

grails-app/views/message/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<div class="container-fluid">
    <g:if test="${flash.message}">
        <div class="alert alert-success mx-auto col-10">
            <div>${flash.message}</div>
        </div>
    </g:if>
    <g:hasErrors bean="${this.game}">
        <div class="alert alert-danger mx-auto col-10">
            <ul>
                <g:eachError bean="${this.game}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                            error="${error}"/></li>
                </g:eachError>
            </ul>
        </div>
    </g:hasErrors>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><g:message code="default.edit.label" args="[entityName]"/></div>
                <g:form resource="${this.message}" method="PUT">
                    <div class="card-body">
                        <g:hiddenField name="version" value="${this.message?.version}"/>
                        <f:all bean="message" except="isRead, content"/>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label" for="content">content</label>

                            <div class="col-md-9">
                                <textarea class="form-control" id="content" name="content" rows="9"
                                          placeholder="Content..">${message.content}</textarea>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <button class="btn btn-sm btn-primary" type="submit">
                            <i class="fa fa-dot-circle-o"></i> ${message(code: 'default.button.update.label', default: 'Update')}
                        </button>
                        <button class="btn btn-sm btn-danger" type="reset">
                            <i class="fa fa-ban"></i> Reset</button>
                    </div>
                </g:form>
            </div>
        </div>
    </div>
</body>
</html>

grails-app/views/message/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="container-fluid">
    <g:if test="${flash.message}">
        <div class="alert alert-success mx-auto col-10">
            <div>${flash.message}</div>
        </div>
    </g:if>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><g:message code="default.list.label" args="[entityName]"/></div>

                <div class="card-body">
                    <table id="tableMessages" class="table table-responsive-sm table-hover table-outline mb-0">
                        <thead class="thead-light">
                        <tr>

                            <th>Author</th>
                            <th>Target</th>
                            <th>Content</th>
                            <th>Is read</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <g:each var="messageObj" in="${messageList}">
                            <tr>
                                <td>
                                    <div class="avatar  index_game">
                                        <g:if test="${messageObj.author.pathProfileImage == null}">
                                            <g:img dir="images" file="user.svg" class="img-avatar"/>
                                        </g:if>
                                        <g:else>
                                            <img class="img-avatar" src="${messageObj.author.pathProfileImage}"/>
                                        </g:else>
                                    </div>
                                    ${messageObj.author.username}
                                </td>
                                <td>
                                    <div class="avatar  index_game">
                                        <g:if test="${messageObj.target.pathProfileImage == null}">
                                            <g:img dir="images" file="user.svg" class="img-avatar"/>
                                        </g:if>
                                        <g:else>
                                            <img class="img-avatar" src="${messageObj.target.pathProfileImage}"/>
                                        </g:else>
                                    </div>
                                    ${messageObj.target.username}
                                </td>
                                <td>
                                    ${messageObj.content.take(20)}
                                    <g:if test="${messageObj.content.length() > 20}">...</g:if>
                                </td>
                                <td>
                                    <g:if test="${messageObj.isRead}">
                                        <i class="icon-check"></i>
                                    </g:if>
                                </td>
                                <td>
                                    <div class="row">
                                        <div class="col-4 col-sm-12 col-md-12 col-xl-4">
                                            <a href="<g:createLink controller="message" action="show"
                                                                   params="[id: messageObj.id]"/>">
                                                <button class="btn btn-block btn-primary" type="button"><g:message
                                                        code="gui.button.learnMore"/></button>
                                            </a>
                                        </div>

                                        <div class="col-4 col-sm-12 col-md-12 col-xl-4">
                                            <a href="<g:createLink controller="message" action="edit"
                                                                   params="[id: messageObj.id]"/>">
                                                <button class="btn btn-block btn-success" type="button"><g:message
                                                        code="default.button.edit.label"/></button>
                                            </a>
                                        </div>

                                        <div class="col-4 col-sm-12 col-md-12 col-xl-4">
                                            <form method="post"
                                                  action="<g:createLink controller="message" action="delete"
                                                                        params="[id: messageObj.id]"/>"
                                                  onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
                                                <input type="hidden" name="_method" value="DELETE" id="_method"/>
                                                <input class="btn btn-block btn-danger" type="submit"
                                                       value="<g:message code="default.button.delete.label"/>"/>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </g:each>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        $('#tableMessages').DataTable({
            responsive: true,
        });
    });
</script>
</body>
</html>

grails-app/views/message/show.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<div class="container-fluid">
    <g:if test="${flash.message}">
        <div class="alert alert-success mx-auto col-10">
            <div>${flash.message}</div>
        </div>
    </g:if>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><g:message code="default.show.label" args="[entityName]"/>
                    <div class="float-right">
                        <a class="card-header-action delete-badge">
                            <g:form resource="${this.message}" method="DELETE">
                                <input type="hidden" name="_method" value="DELETE" id="_method"/>
                                <input class="badge badge-pill badge-danger delete" type="submit"
                                       value="<g:message code="default.button.delete.label"/>">
                            </g:form>
                        </a>
                    </div>

                    <div class="float-right">
                        <a class="card-header-action"
                           href="<g:createLink controller="message" action="edit" params="['id': message.id]"/>">
                            <small class="badge badge-pill badge-success edit"><g:message
                                    code="default.button.edit.label"/></small>
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <div id="rowMessageSend" class="row">
                        <div class="col-10 mx-auto">
                            <div class="avatar  index_game  img-avatar-message">
                                <g:if test="${message.author.pathProfileImage == null}">
                                    <g:img dir="images" file="user.svg" class="img-avatar"/>
                                </g:if>
                                <g:else>
                                    <img class="img-avatar" src="${message.author.pathProfileImage}"/>
                                </g:else>
                            </div>
                            ${message.author.username}
                            <g:img dir="images" file="arrow-pointing-to-right.svg" class="arrow-send"/>
                            <div class="avatar  index_game  img-avatar-message">
                                <g:if test="${message.target.pathProfileImage == null}">
                                    <g:img dir="images" file="user.svg" class="img-avatar"/>
                                </g:if>
                                <g:else>
                                    <img class="img-avatar" src="${message.target.pathProfileImage}"/>
                                </g:else>
                            </div>
                            ${message.target.username}
                        </div>
                    </div>

                    <div class="jumbotron jumbotron-fluid content-message">
                        <div class="container">
                            <h1 class="display-6">Content:</h1>

                            <p class="lead">${message.content}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>